# Outils d'optimisation et d'algèbre linéaire numérique
## Laboratoire 0: Introduction au langage julia
Alexis Montoison, Tangi Migot et Dominique Orban

## a) SOS
Voici quelques conseils pour trouver de la documentation sur Julia et ses fonctionalités.    
i) Utilisez `?` dans Julia donne accès à la documentation des fonctions.

In [1]:
? print

ErrorException: syntax: invalid identifier name "?"

ii) Utiliser la documentation et le manuel en ligne de Julia: [https://docs.julialang.org/en/v1/](https://docs.julialang.org/en/v1/)

iii) Utilisez votre moteur de recherche préféré !

iv) Posez des questions aux professeurs

## b) Types usuels en Julia

### Les chaines de caractères

Une chaine de caractère est representée entre `""`. On peut utiliser la fonction `println` pour les afficher.

In [2]:
println("Hello world")

Hello world


Pour connaître le type d'un objet, on utilise la fonction `typeof`.

In [3]:
typeof("Hello world")

String

### Les entiers et réels flottants
- Les types entiers signés : Int8, Int16, Int32, Int64, Int128;
- Les types entiers non signés : UInt8, UInt16, UInt32, UInt64, UInt128;
- Les réels flottants : Float16, Float32, Float64.

Par défaut, le type d'une variable est définie par son affectation, mais on peut préciser son type.

In [4]:
x = 3
println("valeur de x : ", x, " || type de x : ",typeof(x))
y = UInt64(3)
println("valeur de y : ", y, " || type de y : ",typeof(y))
z = 3.0
println("valeur de z : ", z, " || type de z : ",typeof(z))

valeur de x : 3 || type de x : 

Int64
valeur de y : 3 || type de y : UInt64
valeur de z : 3.0 || type de z : Float64


### Les complexes

In [5]:
c = 3 + 7 * im
println("valeur de c : ", c, " || type de c : ",typeof(c))

valeur de c : 

3 + 7im || type de c : Complex{Int64}


### Les rationnels

In [6]:
r = 4//5
println("valeur de r : ", r, " || type de r : ",typeof(r))
a = 2 // 3
r + a 

valeur de r : 4//5 || type de r : Rational{Int64}


22//15

### Booléens

In [7]:
b = true
println("valeur de b : ", b, " || type de b : ",typeof(b))

valeur de b : true || type de b : Bool


### Itérateurs

In [8]:
it = 3:2:9
println("valeur de it : ", it, " || type de it : ",typeof(it))

valeur de it : 3:2:9 || type de it : StepRange{Int64, Int64}


### Les tuples

In [9]:
t = tuple('c', 3, "MTH")

('c', 3, "MTH")

In [10]:
typeof(t)

Tuple{Char, Int64, String}

Les tuples sont des objets non modifiables!

### Les tableaux

#### **a) Création des vecteurs**

In [11]:
#v = [1; 2; 3]  # Vecteur de longueur 3
v = [1, 2, 3]  # Vecteur de longueur 3

3-element Vector{Int64}:
 1
 2
 3

#### b) Création des matrices

In [13]:
M = [1 2; 3 4]  # Matrice de taille 2 x 2
#M = zeros(2, 2)  # Matrice contenant que des 0 de taille 2 x 2
#M = ones(3, 4)  # Matrice contenant que des 1 de taille 2 x 2

2×2 Matrix{Int64}:
 1  2
 3  4

### Autres types de base
* les chaînes de caractères;
* les dictionnaires;
* ...

On peut aussi créer des types plus évolués comme les structures avec des attributs.

### Commentaires

In [ ]:
# Il s'agit d'un commentaire !

In [ ]:
#=
Il s'agit d'un bloc de commentaires !!!
=#

## c) Caractères unicodes

Les caractères unicodes sont supportés par Julia et permettent d'augmenter la lisibilité d'un code.

In [14]:
β = 20 # on tape \beta puis TAB
α = γ
Ω = 3  # on tape \Omega puis TAB
∇f

UndefVarError: UndefVarError: γ not defined

You write `\nabla` and then press TAB to get the symbol, `∇`.  

## d) Opérations mathématiques

Les opérateurs classiques sont disponibles: `+`, `-`, `*`, `/`, `^`.

In [15]:
2^2

4

Les fonctions usuelles de mathématiques sont également disponibles: exp, sqrt, log, sin, abs, binomial, factorial.

In [16]:
abs(-1)

1

Lorsqu'une fonction s'applique à tous les éléments d'un vecteur on rajoute un `.` à la fin de la fonction. Il s'agit de la vectorisation.

In [17]:
x = [0, 1/4, 1/2, 1]
sin.(x)

4-element Vector{Float64}:
 0.0
 0.24740395925452294
 0.479425538604203
 0.8414709848078965

Les opérateurs suivant permettent de comparer deux objets entre eux: `==`, `===`, `!=`, `<`, `>`, `<=` ou `≤` (\leq puis TAB), `>=` ou `≥` (\geq puis TAB)

In [18]:
1 == 2

false

Les types sont importants et influencent certaines opérations.

In [19]:
(1 == 1.) #!= (1 == 1.) 

true

Dans le cas de **booléens**, les opérateurs suivant sont disponibles: `!` (non), `&` (et), `|` (ou), `xor`/`⊻` (ou exclusif)

In [23]:
true ⊻ true

false

In [24]:
false & (1 == 2)

false

In [25]:
true || (1 == 2)

true

In [26]:
false ⊻ true

true

Il existe certains nombres particuliers: `NaN`, `Inf`, `pi` ...

In [27]:
π
0. /0.
typeof(NaN)

Float64

Il faut faire attention à ces nombres qui peuvent être surprenant. Par exemple pour tester si un objet est un `NaN`, il faut utiliser la fonction `isnan` et pas `==`.

In [28]:
NaN == NaN
Inf < Inf
isnan(NaN)
0. == - 0.

true

Un autre nombre particulier est donné par `eps`, c'est la précision machine.

In [29]:
eps() #par défaut les réels sont des Float64

2.220446049250313e-16

## c) Structures usuelles en Julia

### Boucles for

In [30]:
N = 4
for i in 1:N
   println(i)
end

1
2
3
4


### Boucles while

In [31]:
N = 4
i = 0
while i <= N
   i += 1 #i = i + 1
   println(i)
end

1
2
3
4
5


Les variables créées à l'intérieur d'une boucle sont locales et donc pas accessibles en dehors.

In [39]:
x = 1
for i = 1:3
    x = "hello" # new local
    y = "test"
    if i==2
        break
    end
    #println(x)
end

UndefVarError: UndefVarError: clear not defined

## Conditionnelles

In [40]:
i=1;
N=1;
if i < N
   # ...
elseif i > N 
   # ...
else
   println("Yes!")
end

Yes!


En fonction du contexte, on peut se limiter à une boucle if sans elseif ou else.

In [41]:
if true
    # ...
end

Il existe aussi un opérateur simplifié pour les conditions if-else.

In [ ]:
x, y = 2, 3
x > y ? "x is larger" : "y is larger" 
#= c'est équivalent à
if x>y
  "x is larger"
else
  "y is larger"
end
=#

## d) Fonctions

In [42]:
function f(x)
   return "bon matin"
end
f(1)

"bon matin"

On peut omettre `return`, dans ce cas c'est le contenu de la dernière ligne qui est renvoyé

In [43]:
function f(x)
    "bon matin"
end
f(1)

"bon matin"

On peut aussi avoir plusieurs `return` par fonction et pas forcément à la fin.

In [44]:
function f(x)
    if x == 1
        return "Zzzz"
    end
    return 2 #...
end
f(3)

2

On peut aussi définir les fonctions sur une ligne.

In [45]:
f(x) = println("Zzzz")
f(1)

Zzzz


Lorsqu'on veut rajouter des paramètres optionnels, on utilise un `;` pour les distinguer des autres paramètres. On appelle alors la fonction en précisant le nom de la variable si on n'utilise pas sa valeur pas défaut.

In [46]:
function p(x, y; a=1, b=0)
    a * x * y + b
end
p(3, 1)

3

## e) Dispatch multiple

In [47]:
function h(a::Real, b::Real)
    return a + b
end

function h(a::Int, b::Int)
    return a - b
end

h (generic function with 2 methods)

In [48]:
methods(h)

# 2 methods for generic function "h":
[1] h(a::Int64, b::Int64) in Main at c:\Users\edwar\Desktop\H23\MTH8408\MTH8408\lab1\notebook_0.ipynb:5
[2] h(a::Real, b::Real) in Main at c:\Users\edwar\Desktop\H23\MTH8408\MTH8408\lab1\notebook_0.ipynb:1

In [49]:
h(1.,2.)

3.0

Lorsqu'on va appeler la fonction h, la méthode la plus adaptée à nos arguments sera utilisée!

## f) Parler avec Julia

Lorsqu'il y a un bug, Julia renvoie un message d'erreur qui peut aider à trouver le problème. Quelques exemples:

In [50]:
1 + "hello"

MethodError: MethodError: no method matching +(::Int64, ::String)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:591
  +(::T, !Matched::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Number, !Matched::Base.TwicePrecision) at twiceprecision.jl:294
  ...

In [51]:
sqrt(-1)

DomainError: DomainError with -1.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).

In [52]:
f(x) = x
f(1, 2)

MethodError: MethodError: no method matching f(::Int64, ::Int64)
Closest candidates are:
  f(::Any) at c:\Users\edwar\Desktop\H23\MTH8408\MTH8408\lab1\notebook_0.ipynb:1

In [53]:
undefined_variable

UndefVarError: UndefVarError: undefined_variable not defined

## Exercice: function that solves ax² + bx + c = 0

In [60]:
function f(a, b, c)
    discrimant = b^2 - 4*a*c

    if discrimant == 0
        return -b/(2*a)

    elseif discrimant > 0
        x1 = (-b + sqrt(discrimant))/(2*a)
        x2 = (-b - sqrt(discrimant))/(2*a)
        return (x1, x2)
    else
        return "complex solution"
    end

end

println(f(1,4,1))

(-0.2679491924311228, -3.732050807568877)
