 # MTH8408 : Méthodes d'optimisation et contrôle optimal
 ## Laboratoire 1: Outils pour l'algèbre linéaire et l'optimisation
Tangi Migot

## a) Gestion de l'environement de packages

Certaines des fonctionnalités de Julia sont encapsulées dans des **packages**. C'est le cas des fonctions pour l'algèbre linéaire qui sont dans `LinearAlgebra`.
Pour accèder à l'environement qui gère ces packages on utilise `]`.

Pour ajouter `LinearAlgebra`:

In [1]:
] add LinearAlgebra

ErrorException: syntax: unexpected "]"

Une alternative est d'utiliser le package `Pkg` qui est installer d'office avec Julia.

In [2]:
using Pkg #using permet d'utiliser les fonctionnalités d'un package.
Pkg.add("LinearAlgebra")

    Updating registry at `C:\Users\Goglu\.julia\registries\General.toml`

   Resolving package versions...

  No Changes to `C:\Users\Goglu\.julia\environments\v1.8\Project.toml`
    Updating `C:\Users\Goglu\.julia\environments\v1.8\Manifest.toml`


  [e66e0078] ↑ CompilerSupportLibraries_jll v0.5.2+0 ⇒ v1.0.1+0


Precompiling project...


  ✓ SnoopPrecompile


  ✓ RangeArrays


  ✓ FunctionWrappers


  ✓ StructTypes


  ✓ LaTeXStrings


  ✓ URIParser


  ✓ IndirectArrays
  ✓ Glob


  ✓ ExprTools


  ✓ IteratorInterfaceExtensions


  ✓ SentinelArrays


  ✓ StatsAPI


  ✓ CEnum
  ✓ TensorCore
  ✓ Contour


  ✓ Quaternions


  ✓ InitialValues


  ✓ LinearMaps


  ✓ Pipe
  ✓ UnPack
  ✓ OpenLibm_jll


  ✓ Measures


  ✓ PrettyPrint
  ✓ ArgCheck


  ✓ BufferedStreams

  ✓ WoodburyMatrices


  ✓ FillArrays


  ✓ CompilerSupportLibraries_jll


  ✓ InverseFunctions
  ✓ ShowCases


  ✓ IterTools


  ✓ PkgVersion


  ✓ Grisu


  ✓ Preferences


  ✓ FixedPointNumbers


  ✓ Compat


  ✓ OrderedCollections
  ✓ InternedStrings


  ✓ DataValueInterfaces


  ✓ RealDot


  ✓ StringManipulation


  ✓ Requires
  ✓ Unzip


  ✓ Reexport


  ✓ MbedTLS_jll


  ✓ Zlib_jll


  ✓ MacroTools
  ✓ IniFile


  ✓ DocStringExtensions


  ✓ IntervalSets


  ✓ SimpleBufferStream
  ✓ IrrationalConstants


  ✓ BFloat16s


  ✓ URIs


  ✓ CustomUnitRanges


  ✓ CompositionsBase
  ✓ Parsers


  ✓ PCRE2_jll


  ✓ Formatting


  ✓ ArrayInterfaceCore


  ✓ ProgressMeter
  ✓ DefineSingletons


  ✓ LazyModules


  ✓ InvertedIndices


  ✓ IfElse
  ✓ UnicodeFun


  ✓ Inflate


  ✓ Adapt


  ✓ DataAPI


  ✓ TranscodingStreams


  ✓ ProgressLogging


  ✓ ConstructionBase


  ✓ BitFlags
  ✓ ComputationalResources


  ✓ Scratch


  ✓ LoggingExtras


  ✓ StaticArraysCore


  ✓ Functors
  ✓ TupleTools


  ✓ MappedArrays


  ✓ Crayons


  ✓ GZip


  ✓ TableTraits


  ✓ NaNMath


  ✓ Distances


  ✓ BinDeps
  ✓ Baselet


  ✓ NameResolution


  ✓ RecipesBase


  ✓ TimerOutputs


  ✓ AxisAlgorithms


  ✓ OpenBLAS_jll
  ✓ Showoff


  ✓ ContextVariablesX


  ✓ JLLWrappers


  ✓ Parameters


  ✓ ChainRulesCore


  ✓ Ratios


  ✓ RandomNumbers


  ✓ FilePathsBase


  ✓ LibSSH2_jll


  ✓ ZipFile
  ✓ DataStructures


  ✓ ColorTypes


  ✓ MbedTLS


  ✓ CommonSubexpressions


  ✓ ZygoteRules


  ✓ AxisArrays


  ✓ SimpleTraits


  ✓ FileIO


  ✓ InlineStrings


  ✓ IRTools


  ✓ Static


  ✓ GPUArraysCore


  ✓ PooledArrays


  ✓ Missings


  ✓ OffsetArrays


  ✓ CodecZlib


  ✓ JSON


  ✓ RelocatableFolders


  ✓ DiffResults


  ✓ Latexify


  ✓ Strided


  ✓ Accessors


  ✓ Tables


  ✓ Setfield


  ✓ libblastrampoline_jll


  ✓ FLoopsBase


  ✓ OpenSSL_jll


  ✓ Graphite2_jll


  ✓ Libmount_jll


  ✓ JSON3


  ✓ MLStyle


  ✓ Bzip2_jll
  ✓ Xorg_libXau_jll


  ✓ IterativeSolvers


  ✓ libpng_jll


  ✓ libfdk_aac_jll


  ✓ Imath_jll


  ✓ IntelOpenMP_jll


  ✓ LAME_jll


  ✓ Pixman_jll


  ✓ LERC_jll


  ✓ fzf_jll


  ✓ JpegTurbo_jll


  ✓ Ogg_jll
  ✓ Xorg_libXdmcp_jll


  ✓ x265_jll


  ✓ x264_jll


  ✓ LLVMExtra_jll


  ✓ libaom_jll


  ✓ Expat_jll
  ✓ Zstd_jll


  ✓ LZO_jll


  ✓ Opus_jll


  ✓ Xorg_xtrans_jll


  ✓ Libiconv_jll


  ✓ Libffi_jll
  ✓ Libgpg_error_jll

  ✓ Wayland_protocols_jll


  ✓ StaticArrays
  ✓ FFTW_jll


  ✓ OpenSpecFun_jll


  ✓ Xorg_libpthread_stubs_jll


  ✓ FriBidi_jll
  ✓ Libuuid_jll


  ✓ AbstractFFTs


  ✓ ChangesOfVariables


  ✓ SortingAlgorithms


  ✓ Random123
  ✓ Optimisers


  ✓ IntegralArrays


  ✓ QOI


  ✓ ArrayInterface
  ✓ WeakRefStrings
  ✓ TiledIteration


  ✓ StackViews
  ✓ CatIndices
  ✓ PaddedViews

  ✓ NNlib


  ✓ StructArrays


  ✓ Colors
  ✓ SplittablesBase

  ✓ HDF5_jll


  ✓ OpenSSL


  ✓ BangBang


  ✓ FreeType2_jll


  ✓ OpenEXR_jll


  ✓ MKL_jll


  ✓ JLFzf


  ✓ libsixel_jll


  ✓ libvorbis_jll


  ✓ Libtiff_jll


  ✓ StringEncodings


  ✓ XML2_jll


  ✓ Libgcrypt_jll


  ✓ PrettyTables


  ✓ JuliaVariables


  ✓ ArnoldiMethod


  ✓ CoordinateTransformations


  ✓ LLVM


  ✓ NearestNeighbors


  ✓ Rotations


  ✓ MosaicViews

  ✓ RegionTrees


  ✓ JLD2


  ✓ LogExpFunctions


  ✓ Graphics


  ✓ Interpolations


  ✓ MicroCollections


  ✓ Fontconfig_jll


  ✓ CSV


  ✓ HTTP


  ✓ OpenEXR


  ✓ ImageMagick_jll


  ✓ Gettext_jll


  ✓ Wayland_jll


  ✓ HDF5


  ✓ ChainRules


  ✓ XSLT_jll


  ✓ Pickle


  ✓ FFTW


  ✓ GPUArrays


  ✓ StatsBase


  ✓ DataDeps


  ✓ SpecialFunctions


  ✓ Graphs


  ✓ Transducers


  ✓ Glib_jll


  ✓ Xorg_libxcb_jll


  ✓ GPUCompiler


  ✓ MAT


  ✓ FFTViews


  ✓ DiffRules


  ✓ Clustering


  ✓ FoldsThreads


  ✓ SimpleWeightedGraphs


  ✓ ColorVectorSpace


  ✓ Xorg_xcb_util_jll


  ✓ Xorg_libX11_jll


  ✓ MetaGraphs


  ✓ ForwardDiff


  ✓ Xorg_xcb_util_image_jll


  ✓ FLoops


  ✓ Xorg_xcb_util_keysyms_jll


  ✓ ColorSchemes


  ✓ Xorg_xcb_util_renderutil_jll


  ✓ Xorg_xcb_util_wm_jll


  ✓ Xorg_libXrender_jll


  ✓ Xorg_libXext_jll


  ✓ Xorg_libXfixes_jll
  ✓ Xorg_libxkbfile_jll


  ✓ DataFrames


  ✓ Libglvnd_jll


  ✓ Xorg_libXinerama_jll


  ✓ MLUtils


  ✓ Xorg_libXrandr_jll


  ✓ PlotUtils


  ✓ Cairo_jll


  ✓ Xorg_libXcursor_jll


  ✓ Xorg_libXi_jll


  ✓ Zygote


  ✓ TiffImages


  ✓ Xorg_xkbcomp_jll


  ✓ OneHotArrays


  ✓ RecipesPipeline


  ✓ PlotThemes


  ✓ HarfBuzz_jll


  ✓ GLFW_jll
  ✓ Xorg_xkeyboard_config_jll


  ✓ libass_jll


  ✓ xkbcommon_jll


  ✓ Qt5Base_jll
  ✓ FFMPEG_jll


  ✓ MatrixDepot


  ✓ ImageCore


  ✓ FFMPEG


  ✓ GR_jll


  ✓ MLDatasets


  ✓ ImageMorphology

  ✓ ImageBase


  ✓ JpegTurbo


  ✓ Sixel


  ✓ ImageMagick


  ✓ Netpbm


  ✓ GR


  ✓ ImageDistances


  ✓ PNGFiles


  ✓ ImageIO


  ✓ ImageShow


  ✓ ImageAxes


  ✓ ImageTransformations


  ✓ CUDA


  ✓ ImageMetadata


  ✓ ImageContrastAdjustment


  ✓ NNlibCUDA


  ✓ ImageFiltering


  ✓ ImageQualityIndexes


  ✓ ImageSegmentation


  ✓ Flux


  ✓ Images


  ✓ Plots


  302 dependencies successfully precompiled in 210 seconds


Pour l'utiliser dans notre environement, on utilise `using`.

In [3]:
using LinearAlgebra

Si vous ne savez plus quels packages sont installés ou vous souhaitez connaître la version des packages installés, on utilise `status`.

In [4]:
] status

ErrorException: syntax: unexpected "]"

## b) Algèbre linéaire

### **i) Création des vecteurs**

In [5]:
v = [1; 2; 3]  # Vecteur de longueur 3
v = [1, 2, 3]  # Vecteur de longueur 3

3-element Vector{Int64}:
 1
 2
 3

In [9]:
typeof(v)

Vector{Int64} (alias for Array{Int64, 1})

Les tableaux (Array) ont un type particulier en Julia, il est paramétrique. On fait la différence entre un tableau de réels ou d'entiers.

### ii) Création des matrices

In [7]:
M = [1 2; 3 4]  # Matrice de taille 2 x 2
M = zeros(2, 2)  # Matrice contenant que des 0 de taille 2 x 2
M = ones(2, 2)  # Matrice contenant que des 1 de taille 2 x 2
M = I  # Matrice identité dont la dimension s'adapte aux opérations

UniformScaling{Bool}
true*I

In [13]:
v = [1, 2, 3]
M = Diagonal(v) #matrice avec v sur la diagonale
# M = diagm(0 => v)
M = diagm(-1 => v)

4×4 Matrix{Int64}:
 0  0  0  0
 1  0  0  0
 0  2  0  0
 0  0  3  0

In [14]:
x = [1, 2, 3]
y = [4, 5, 6, 7]
z = [8, 9, 10]
N = Tridiagonal(x, y, z)  # Création d'une matrice tridiagonale

4×4 Tridiagonal{Int64, Vector{Int64}}:
 4  8  ⋅   ⋅
 1  5  9   ⋅
 ⋅  2  6  10
 ⋅  ⋅  3   7

In [15]:
M = [1 2; 3 4]
typeof(M)

Matrix{Int64} (alias for Array{Int64, 2})

### iii) Manipulation des vecteurs et des matrices

In [16]:
transpose(M)  # Matrice transposéee Mᵀ
M'  # Matrice adjointe Mᴴ (transposée de la matrice conjuguée)

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

In [17]:
#M = hcat([1 2], [1 2]) # Concaténation horizontale
M = vcat([1 2], [1 2]) #  Concaténation verticale

2×2 Matrix{Int64}:
 1  2
 1  2

Accès aux composants d'un vecteur ou d'une matrice

In [18]:
M = [1 2; 3 4]
M[2, 2] # Accès au coefficient (2, 2) de M
M[1:2, 1]  # Accès aux lignes 1 à 2 de M
D = diag(M)  # Vecteur contenant la diagonale de la matrice M
nrow, ncol = size(M)  # Dimensions de la matrices M 

(2, 2)

In [19]:
#LowerTriangular(M)  # Triangle inférieur de M
#UpperTriangular(M)  # Triangle supérieur de M
tril(M)
#triu(M)
#UnitLowerTriangular(M)  # Triangle strictement inférieur de M avec diagonale unitaire
#UnitUpperTriangular(M)  # Triangle strictement supérieur de M avec diagonale unitaire

2×2 Matrix{Int64}:
 1  0
 3  4

### iv) Opérations mathématiques

In [20]:
A = ones(2,2)
B = [1 2; 3 4]
A * B  # Produit matriciel de A et B

2×2 Matrix{Float64}:
 4.0  6.0
 4.0  6.0

In [ ]:
A .* B  # Produit des coefficients termes à termes

In [ ]:
1 .+ A #ajoute 1 à toutes les composantes de A

In [ ]:
inv(B)  # Inverse d'une matrice

In [ ]:
det(A)  # Déterminant d'une matrice

In [ ]:
tr(A)  # Trace d'une matrice

In [ ]:
val, vec = eigen(A)  # Valeurs propres et vecteurs propres de A
val

In [ ]:
b = B * ones(2)
x = B \ b  # Résolution du système linéaire Ax = b

In [27]:
function check_matrix_is_symmetric_pos_def(A)
    is_symmetric = (A == transpose(A))

    if is_symmetric
        eigenvalues = eigvals(A)
        is_pos = true
        for value in eigenvalues
            is_pos = (value >= 0)
            if !is_pos
                break
            end
        end
        if is_pos
            return "A is symmetric positive definite"
        else
            return "A is symmetric, but not positive definite"
        end
    else
        return "A is not symmetric"
    end
end

A = [1 0; 0 -1]
check_matrix_is_symmetric_pos_def(A)

"A is symmetric, but not positive definite"