 # MTH8408 : Méthodes d'optimisation et contrôle optimal
 ## Laboratoire 2: Optimisation sans contraintes
Tangi Migot

In [94]:
using ADNLPModels, LinearAlgebra, NLPModels, Printf

On pourra trouver de la documentation sur `ADNLPModels` et `NLPModels` ici:
- [juliasmoothoptimizers.github.io/NLPModels.jl/dev/](https://juliasmoothoptimizers.github.io/NLPModels.jl/dev/)
- [juliasmoothoptimizers.github.io/ADNLPModels.jl/dev/](https://juliasmoothoptimizers.github.io/ADNLPModels.jl/dev/)

In [95]:
# Problème test:
f(x) = x[1]^2 * (2*x[1] - 3) - 6*x[1]*x[2] * (x[1] - x[2] - 1) # fonction objectif vue en classe
g(x) = 6 * [x[1]^2 - x[1] - 2*x[1]*x[2] + x[2]^2 + x[2]; -x[1]^2 + 2*x[1]*x[2] + x[1]] # le gradient de f
H(x) = 6 * [2*x[1]-1-2*x[2] -2*x[1]+2*x[2]+1; -2*x[1]+2*x[2]+1 2*x[1]] # la Hessienne de f

H (generic function with 1 method)

### Exercice 1: Newton avec recherche linéaire - amélioration du code

Ci-dessous, vous avez le code de deux fonctions qui ont été vues dans le cours, la recherche linéaire qui satisfait Armijo, et une méthode de Newton avec cette recherche linéaire. Le but de ce laboratoire est d'implémenter d'autres méthodes utiles pour résoudre des problèmes de grandes dimensions.

In [96]:
#Amélioration possibles: return also the value of f
function armijo(xk, dk, fk, gk, f)
  slope = dot(gk, dk) #doit être <0
  t = 1.0
  while f(xk + t * dk) > fk + 1.0e-4 * t * slope
    t /= 1.5
  end
  return t
end

armijo (generic function with 1 method)

In [97]:
#Test pour vérifier que la fonction armijo fonctionne correctement.
using Test #le package Test définit (entre autre) la macro @test qui permet de faire des tests unitaires :-)
xk = ones(2)
gk = g(xk)
dk = - gk
fk = f(xk)
t  = armijo(xk, dk, fk, gk, f)
@test t < 1
@test f(xk + t * dk) <= fk + 1.0e-4 * t * dot(gk,dk)

xk = [1.5, 0.5]
fk = f(xk)
gk = g(xk)
dk = - gk
t  = armijo(xk, dk, fk, gk, f)
@test t < 1
@test f(xk + t * dk) <= f(xk) + 1.0e-4 * t * dot(g(xk),dk)


Test Passed
  Expression: f(xk + t * dk) <= f(xk) + 0.0001 * t * dot(g(xk), dk)
   Evaluated: -0.37311385459533614 <= -0.00017777777777777779

In [98]:
function newton_armijo(f, g, H, x0; verbose::Bool = true)
  xk  = x0
  fk  = f(xk)
  gk = g(xk)
  gnorm = gnorm0 = norm(gk)
  k = 0
  verbose && @printf "%2s %9s %9s\n" "k" "fk" "||∇f(x)||"
  verbose && @printf "%2d %9.2e %9.1e\n" k fk gnorm
  while gnorm > 1.0e-6 + 1.0e-6 * gnorm0 && k < 100
    Hk = H(xk)
    dk = - Hk \ gk
    slope = dot(dk, gk)
    λ = 0.0
    while slope ≥ -1.0e-4 * norm(dk) * gnorm
      λ = max(1.0e-3, 10 * λ)
      dk = - ((Hk + λ * I ) \ gk)
      slope = dot(dk, gk)
    end
    t = armijo(xk, dk, fk, gk, f)
    xk += t * dk
    fk = f(xk)
    gk = g(xk)
    gnorm = norm(gk)
    k += 1
    verbose && @printf "%2d %9.2e %9.1e %7.1e \n" k fk gnorm t
  end
  return xk
end

newton_armijo (generic function with 2 methods)

In [99]:
sol = newton_armijo(f, g, H, [.5, .5])
@test g(sol) ≈ zeros(2) atol = 1.0e-6

 k        fk ||∇f(x)||
 0  1.00e+00   4.5e+00
 1  5.08e-02   8.4e-01 1.0e+00 
 2  4.73e-04   7.6e-02 1.0e+00 
 3  6.97e-08   9.1e-04 1.0e+00 
 4  1.62e-15   1.4e-07 1.0e+00 


Test Passed
  Expression: ≈(g(sol), zeros(2), atol = 1.0e-6)
   Evaluated: ≈([0.0, 1.3938344522837628e-7], [0.0, 0.0]; atol = 1.0e-6)

On veut améliorer le code de la fonction `newton_armijo` avec les ajouts suivants:
- Changer les paramètre d'entrées de la fonction pour un `nlp`
- Avant d'appeler la recherche linéaire, si `slope = dot(dk, gk)` est plus grand que `-1.0e-4 * norm(dk) * gnorm`, on modifie le système. On fait maximum 5 mise à jour de `λ`, sinon on prend l'opposé du gradient.
```
    λ = 0.0
    while slope ≥ -1.0e-4 * norm(dk) * gnorm
      λ = max(1.0e-3, 10 * λ)
      dk = - ((Hk + λ * I ) \ gk)
      slope = dot(dk, gk)
    end
```
Ajouter un compteur sur le nombre de mises à jour de `λ` et ajuster `dk = - gk` si la limite est atteinte.
- On veut aussi détecter et éventuellement arrêter la boucle `while` si la fonction objectif `fk` devient trop petite/négative (inférieure à `-1e15`), i.e. le problème est non-bornée inférieurement.
- On veut ajouter deux critères d'arrêts supplémentaires: 
  - un compteur sur le nombre d'évaluations de f (maximum 1000). Utiliser `neval_obj(nlp)`.
  -  une limite de temps d'execution, `max_time = 60.0`. Utiliser la fonction `time()`.
- Enfin, on voudrait aussi voir un message à l'écran si l'algorithme n'a pas trouvé la solution, i.e. il s'est arrêté à cause de la limite sur le nombre d'itérations, temps, évaluation de fonctions, problème non-borné.

In [100]:
#SOLUTION: fonction à modifier
function newton_armijo(nlp, x0; verbose::Bool = true)
  xk  = x0
  fk  = obj(nlp, xk)
  gk = grad(nlp,xk)
  gnorm = gnorm0 = norm(gk)

  k = 0
  v = true
  max_time = 60.0
  elapsed_time = 0.0

  verbose && @printf "%2s %9s %9s\n" "k" "fk" "||∇f(x)||"
  verbose && @printf "%2d %9.2e %9.1e\n" k fk gnorm

  start_time = time()
  while gnorm > 1.0e-6 + 1.0e-6 * gnorm0 && k < 100 && v && neval_obj(nlp) <= 1000 && elapsed_time <= max_time
    Hk = hess(nlp, xk)
    dk = - Hk \ gk
    slope = dot(dk, gk)

    λ = 0.0
    c = 1

    while (slope ≥ -1.0e-4 * norm(dk) * gnorm) &&  c < 6
      λ = max(1.0e-3, 10 * λ)
      dk = - ((Hk + λ * I ) \ gk)
      slope = dot(dk, gk)
      c += 1
    end

    if c == 6
      dk = -gk
    end


    t = armijo(xk, dk, fk, gk, x->obj(nlp,x))
    xk += t * dk
    fk = obj(nlp, xk)

    if fk < -1e15
      v = false
    end

    gk = grad(nlp, xk)
    gnorm = norm(gk)
    k += 1
    verbose && @printf "%2d %9.2e %9.1e %7.1e \n" k fk gnorm t

    elapsed_time = time() - start_time
  end


  if !v
    println("problème non-borné négativement")
    
  elseif gnorm <= 1.0e-6 + 1.0e-6 * gnorm0
    println("convergence obtenue")

  elseif neval_obj(nlp) > 1000
    println("budget d'évaluation de f dépassé")

  elseif elapsed_time > max_time
    println("temps maximal dépassé")
  end


  return xk
end

newton_armijo (generic function with 2 methods)

In [101]:
#Test
f(x) = x[1]^2 * (2*x[1] - 3) - 6*x[1]*x[2] * (x[1] - x[2] - 1)
x0 = ones(2)
nlp = ADNLPModel(f, x0)

newton_armijo(nlp, x0)

 k        fk ||∇f(x)||
 0  5.00e+00   1.2e+01
 1  4.07e-01   2.7e+00 1.0e+00 
 2  1.39e-02   4.3e-01 1.0e+00 
 3  4.63e-05   2.4e-02 1.0e+00 
 4  6.99e-10   9.2e-05 1.0e+00 
 5  1.63e-19   1.4e-09 1.0e+00 
convergence obtenue


2-element Vector{Float64}:
 2.3283064370807974e-10
 2.3283064370807974e-10

In [102]:
using Test
#TODO : work on function to match with the tests. 


@testset "Test set for newton_armijo" begin
    #Test problem:
    fH(x) = (x[2]+x[1].^2-11).^2+(x[1]+x[2].^2-7).^2
    x0H = [10., 20.]
    himmelblau = ADNLPModel(fH, x0H)

    problem2 = ADNLPModel(x->-x[1]^3 + x[2]^2 + x[3]^2, ones(3))

    roz(x) = 100 *  (x[2] - x[1]^2)^2 + (x[1] - 1.0)^2
    rosenbrock = ADNLPModel(roz, [-1.2, 1.0])

    f(x) = x[1]^2 * (2*x[1] - 3) - 6*x[1]*x[2] * (x[1] - x[2] - 1)
    pb_du_cours = ADNLPModel(f, [-1.001, -1.001]) #ou [1.5, .5] ou [.5, .5]


    ######################################### newton_armijo ##################

    #=
    Vérifiez que vous pouvez mettre une limite de temps de 1s.
    Puis faites tourner votre algorithme sur un des probléme test.
    L'algorithme devrait s'arrêter en environ 1sec.

    Vérifiez que vous pouvez mettre une limite de 2 évaluations d'objectif.
    Puis faites tournez votre algorithme sur un des probléme test.
    L'algorithme devrait s'arrêter en environ 1 itération.
    =#

    #Unit/Validation Tests
    ep1 = 1e-6 + norm(grad(himmelblau, himmelblau.meta.x0)) * 1e-6
    sol = newton_armijo(himmelblau, himmelblau.meta.x0, verbose = false)
    @test norm(grad(himmelblau, sol)) ≤ ep1
    @test sol ≈ [3, 2] atol = ep1

    ep2 = 1e-6 + norm(grad(problem2, problem2.meta.x0)) * 1e-6
    sol =  newton_armijo(problem2, problem2.meta.x0, verbose = false)
    # @test stats.status == :unbounded
    @test obj(problem2, sol) ≤ -1e15

    ep2 = 1e-6 + norm(grad(rosenbrock, rosenbrock.meta.x0)) * 1e-6
    sol = newton_armijo(rosenbrock, rosenbrock.meta.x0, verbose = false)
    @test sol ≈ [1., 1.] atol = ep2

    ep3 = 1e-6 + norm(grad(pb_du_cours, [-1.001, -1.001])) * 1e-6
    sol = newton_armijo(pb_du_cours, [-1.001, -1.001], verbose = false)
    @test norm(grad(pb_du_cours, sol)) ≤ ep3 || obj(pb_du_cours, sol) <= -1e15

    ep4 = 1e-6 + norm(grad(pb_du_cours, [1.5, .5])) * 1e-6
    sol = newton_armijo(pb_du_cours, [1.5, .5], verbose = false)
    @test norm(grad(pb_du_cours, sol)) ≤ ep4 || obj(pb_du_cours, sol) <= -1e15

    ep5 = 1e-6 + norm(grad(pb_du_cours, [.5, .5])) * 1e-6
    sol = newton_armijo(pb_du_cours, [.5, .5], verbose = false)
    @test norm(grad(pb_du_cours, sol)) ≤ ep5 || obj(pb_du_cours, sol) <= -1e15
end

convergence obtenue
problème non-borné négativement
convergence obtenue
problème non-borné négativement
convergence obtenue
convergence obtenue
Test Summary:              | Pass  Total
Test set for newton_armijo |    7      7


Test.DefaultTestSet("Test set for newton_armijo", Any[], 7, false, false)

### Exercice 2: LDLt-Newton avec recherche linéaire

On va maintenant modifier la méthode de Newton vue précédemment pour utiliser un package qui s'occupe de calculer une factorisation de la matrice hessienne tel que:
$$
\nabla^2 f(x) = LDL^T.
$$
Ce type de factorisation n'est possible que si la matrice hessienne est définie positive, dans le cas contraire on a besoin de régulariser le système comme dans l'exercice précédent.

Pour résoudre le système linéaire en utilisant cette factorisation, on va utiliser le package [`LDLFactorizations`](https://github.com/JuliaSmoothOptimizers/LDLFactorizations.jl):

In [17]:
using LDLFactorizations, LinearAlgebra

Un tutoriel sur l'utilisation de `LDLFactorizations` est disponible sur la documentation du package sur github ou encore [à ce lien](https://juliasmoothoptimizers.github.io/LDLFactorizations.jl/dev/tutorial/).

Voici un exemple d'utilisation de ce package. La matrice dont on veut calculer la factorisation doit être de type `Symmetric`.

In [23]:
A = ones(2,2) #cette matrice symétrique, mais pas du type Symmetric
              #à noter que cette matrice n'est pas définie positive.
typeof(A) <: Symmetric #false
A = Symmetric(A)
typeof(A) <: Symmetric #true :)

true

Deuxième étape, le package fait une phase d'analyse de la matrice avec `ldl_analyze` en créant une structure pratique pour les diverses fonctions du package.

In [103]:
A = -rand(2, 2)
sol = rand(2)
b = A*sol #on veut résoudre le système A*x=b

# LDLFactorizations va en réalité demander la matrice triangulaire supérieure
A = Symmetric(triu(A), :U)
S = ldl_analyze(A)
ldl_factorize!(A, S)
x = S \ b # x = A \b ça va être résolu par Julia 
norm(A * x - b)

0.0

In [104]:
A = [0. 1.; 1. 0.]

2×2 Matrix{Float64}:
 0.0  1.0
 1.0  0.0

In [105]:
A = Symmetric(triu(A), :U)
S = ldl_analyze(A)
ldl_factorize!(A, S)

LDLFactorizations.LDLFactorization{Float64, Int64, Int64, Int64}(true, false, true, 2, [2, -1], [0, 0], [1, 2], [1, 2], [1, 2], [1, 2, 2], [1, 1, 1], Int64[], [4704184112], [0.0], [0.0, 5.0e-324], [0.0, 3.0e-323], [6028030512, 6028030576], 0.0, 0.0, 0.0, 2)

In [106]:
S.d

2-element Vector{Float64}:
 0.0
 5.0e-324

La matrice `A` factorisée par $LDL^T$ n'était pas forcément définie positive. On peut le voir sur les valeurs de $D$.

In [107]:
S.d #c'est le vecteur qui correspond à la matrice diagonale D.

2-element Vector{Float64}:
 0.0
 5.0e-324

Pour l'optimisation, dans le cas où des valeurs de $D$ sont négatives, i.e. `minimum(S.d) <= 0.`, on ajoutera une correction pour être sûr d'obtenir une direction de descente. On pourra choisir un des deux:
- `S.d   = abs.(S.d)`
- `S.d .+= -minimum(S.d) + 1e-6`

#### Utiliser cette technique pour calculer la direction de descente:

In [108]:
# Solution: modifier le calcul de la direction avec LDLFactorizations
function newton_ldlt_armijo(nlp, x0; verbose::Bool = true)
  xk  = x0
  fk  = obj(nlp, xk)
  gk = grad(nlp, xk)
  gnorm = gnorm0 = norm(gk)
  k = 0
  verbose && @printf "%2s %9s %9s\n" "k" "fk" "||∇f(x)||"
  verbose && @printf "%2d %9.2e %9.1e\n" k fk gnorm
  while gnorm > 1.0e-6 + 1.0e-6 * gnorm0 && k < 100 && fk > -1e15
    Hk = Symmetric(triu(hess(nlp, xk)), :U)
    
    Sk = ldl_analyze(Hk)
    ldl_factorize!(Hk, Sk)
    Sk.d = abs.(Sk.d)

    dk = - Sk \ gk
    slope = dot(dk, gk)
    t = armijo(xk, dk, fk, gk, x -> obj(nlp, x))
    xk += t * dk
    fk = obj(nlp, xk)
    gk = grad(nlp, xk)
    gnorm = norm(gk)
    k += 1
    verbose && @printf "%2d %9.2e %9.1e %7.1e \n" k fk gnorm t
  end
  return xk
end

newton_ldlt_armijo (generic function with 1 method)

In [113]:
#Test
f(x) = x[1]^2 * (2*x[1] - 3) - 6*x[1]*x[2] * (x[1] - x[2] - 1)
nlp = ADNLPModel(f, zeros(2))

newton_ldlt_armijo(nlp, x0)

 k        fk ||∇f(x)||
 0  5.00e+00   1.2e+01
 1  4.07e-01   2.7e+00 1.0e+00 
 2  1.39e-02   4.3e-01 1.0e+00 
 3  4.63e-05   2.4e-02 1.0e+00 
 4  6.99e-10   9.2e-05 1.0e+00 
 5  1.63e-19   1.4e-09 1.0e+00 


2-element Vector{Float64}:
 2.328302533919095e-10
 2.328306437046916e-10

In [114]:
using Test

@testset "Test set for newton_ldlt_armijo" begin
    #Test problem:
    fH(x) = (x[2]+x[1].^2-11).^2+(x[1]+x[2].^2-7).^2
    x0H = [10., 20.]
    himmelblau = ADNLPModel(fH, x0H)

    problem2 = ADNLPModel(x->-x[1]^3 + x[2]^2 + x[3]^2, ones(3))

    roz(x) = 100 *  (x[2] - x[1]^2)^2 + (x[1] - 1.0)^2
    rosenbrock = ADNLPModel(roz, [-1.2, 1.0])

    f(x) = x[1]^2 * (2*x[1] - 3) - 6*x[1]*x[2] * (x[1] - x[2] - 1)
    pb_du_cours = ADNLPModel(f, [-1.001, -1.001]) #ou [1.5, .5] ou [.5, .5]

    #Unit/Validation Tests
    ep1 = 1e-6 + norm(grad(himmelblau, himmelblau.meta.x0)) * 1e-6
    sol = newton_ldlt_armijo(himmelblau, himmelblau.meta.x0, verbose = false)
    @test norm(grad(himmelblau, sol)) ≤ ep1
    @test sol ≈ [3, 2] atol = ep1

    ep2 = 1e-6 + norm(grad(problem2, problem2.meta.x0)) * 1e-6
    sol = newton_ldlt_armijo(problem2, problem2.meta.x0, verbose = false)
    # @test stats.status == :unbounded
    @test obj(problem2, sol) ≤ -1e15

    ep2 = 1e-6 + norm(grad(rosenbrock, rosenbrock.meta.x0)) * 1e-6
    sol = newton_ldlt_armijo(rosenbrock, rosenbrock.meta.x0, verbose = false)
    @test sol ≈ [1., 1.] atol = ep2

    ep3 = 1e-6 + norm(grad(pb_du_cours, [-1.001, -1.001])) * 1e-6
    sol = newton_ldlt_armijo(pb_du_cours, [-1.001, -1.001], verbose = false)
    @test norm(grad(pb_du_cours, sol)) ≤ ep3 || obj(pb_du_cours, sol) <= -1e15

    ep4 = 1e-6 + norm(grad(pb_du_cours, [1.5, .5])) * 1e-6
    sol = newton_ldlt_armijo(pb_du_cours, [1.5, .5], verbose = false)
    @test norm(grad(pb_du_cours, sol)) ≤ ep4 || obj(pb_du_cours, sol) <= -1e15

    ep5 = 1e-6 + norm(grad(pb_du_cours, [.5, .5])) * 1e-6
    sol = newton_ldlt_armijo(pb_du_cours, [.5, .5], verbose = false)
    @test norm(grad(pb_du_cours, sol)) ≤ ep5 || obj(pb_du_cours, sol) <= -1e15
end

Test Summary:                   | Pass  Total
Test set for newton_ldlt_armijo |    7      7


Test.DefaultTestSet("Test set for newton_ldlt_armijo", Any[], 7, false, false)

### Exercice 3: Méthode quasi-Newton: BFGS

#### Méthode quasi-Newton: BFGS
Pour des problèmes de très grandes tailles, il est parfois très coûteux d'évaluer la hessienne du problème d'optimisation (et même le produit hessienne-vecteur). La famille des méthode *quasi-Newton* construit une approximation $B_k$ symétrique définie positive de la matrice Hessienne en utilisant seulement le gradient et en mesurant sa variation, et permet quand même d'améliorer significativement les performances comparé à la méthode du gradient.
$$
s_k = x_{k+1} - x_k, \quad y_k = \nabla f(x_{k+1}) - \nabla f(x_k).
$$
Par ailleurs la matrice $B_k$ est aussi construite de façon à ce que l'inverse soit connue, il n'y a donc pas de système linéaire à résoudre.

La méthode la plus connue dans la famille des méthodes quasi-Newton, est la méthode BFGS (Broyden - Fletcher, Goldfarb, and Shanno), et utilise la formule suivante pour calculer l'inverse de $B_k$ que l'on note $H_k$:
$$
H_{k+1} = (I - \rho_k s_ky_k^T)H_k(I-\rho_ky_ks_k^T) + \rho_ks_ks_k^T, \quad \rho_k = \frac{1}{y_k^Ts_k}.
$$
L'algorithme est presque le même que la méthode de Newton à la différence qu'il n'y a pas de système linéaire à résoudre et la direction $d_k$ est à coup sûr une direction de descente. Ainsi la direction de descente est calculée comme suit:
$$
d_k = - H_k \nabla f(x_k).
$$

Comment choisir la matrice $H_0$? On peut éventuellement choisir $I$. Une alternative est d'utiliser $H_0=I$ pour la première itération et ensuite mettre $H_0$ à jour avant de calculer $H_1$ en utilisant:
$$
H_0 = \frac{y_k^Ts_k}{y_k^Ty_k}I.
$$

**Important**: pour s'assurer que la matrice $H_k$ reste définie positive à toutes les itérations, il faut s'assurer que $y_k^Ts_k>0$. C'est toujours vrai pour des fonctions convexes, mais pas nécessairement dans le cas général. On pourra tester ici la version "skip" qui ne mets pas à jour quand cette condition n'est pas vérifiée.

In [143]:
# Solution: copier-coller votre newton_armijo ici et modifier le calcul de la direction avec la méthode de BFGS inverse skip.

function bfgs_quasi_newton_armijo(nlp, x0; verbose::Bool = true)
  xk = x0
  fk = f0 = obj(nlp, xk)
  gk = g0 = grad(nlp,xk)
  gnorm = gnorm0 = norm(gk)
  Hk = H0 = 1.0 * Matrix(I, length(x0), length(x0))
  dk = d0 = -H0*gk
  k = 0

  Xk = [xk]
  Fk = [fk]
  Gk = [gk]
  Gnorm = [gnorm]
  HHk = [Hk]
  Dk = [dk]
  v = true
  max_time = 60.0
  elapsed_time = 0.0

  verbose && @printf "%2s %9s %9s\n" "k" "fk" "||∇f(x)||"
  verbose && @printf "%2d %9.2e %9.1e\n" k fk gnorm

  start_time = time()
  while Gnorm[end] > 1.0e-6 + 1.0e-6 * gnorm0 && k < 100 && v && neval_obj(nlp) <= 1000 && elapsed_time <= max_time

    
    t = armijo(Xk[end], Dk[end], Fk[end], Gk[end], x->obj(nlp,x))
    push!(Dk, -HHk[end]*Gk[end])
    push!(Xk, Xk[end] + t * Dk[end])
    push!(Fk, obj(nlp, Xk[end]))
    push!(Gk, grad(nlp, Xk[end]))
    push!(Gnorm, norm(Gk[end]))

    if Fk[end] < -1e15
      v = false
    end


    sk = Xk[end] - Xk[end-1]
    yk = Gk[end] - Gk[end-1]

    if (yk' * sk) > 0
      ρk = 1/(yk' * sk)
      push!(HHk, (I - ρk*sk*yk')*HHk[end]*(I - ρk*yk*sk') + ρk*sk*sk')
    end



    k += 1
    verbose && @printf "%2d %9.2e %9.1e %7.1e \n" k Fk[end] Gnorm[end] t

    elapsed_time = time() - start_time
  end


  if !v
    println("problème non-borné négativement")
    
  elseif Gnorm[end] <= 1.0e-6 + 1.0e-6 * gnorm0
    println("convergence obtenue")

  elseif neval_obj(nlp) > 1000
    println("budget d'évaluation de f dépassé")

  elseif elapsed_time > max_time
    println("temps maximal dépassé")
  end


  return Xk[end]
end

 k        fk ||∇f(x)||
 0  5.00e+00   1.2e+01


bfgs_quasi_newton_armijo (generic function with 1 method)

In [144]:
#Test
f(x) = x[1]^2 * (2*x[1] - 3) - 6*x[1]*x[2] * (x[1] - x[2] - 1)
nlp = ADNLPModel(f, zeros(2))
x0 = [1. ; 1.]
bfgs_quasi_newton_armijo(nlp, x0)

 k        fk ||∇f(x)||
 0  5.00e+00   1.2e+01
 1  1.02e+00   8.9e+00 1.3e-01 
 2  1.02e+00   8.9e+00 3.7e-18 
 3 -1.19e+01   3.1e+01 1.0e+00 
 4 -6.51e+03   1.8e+03 1.0e+00 
 5 -1.01e+09   5.2e+06 1.0e+00 
 6 -2.26e+19   4.1e+13 1.0e+00 
problème non-borné négativement


2-element Vector{Float64}:
      -2.7269422779089995e6
 -492364.5255340882

In [146]:
@testset "Test set for bfgs_quasi_newton_armijo" begin
	#Test problem:
	fH(x) = (x[2]+x[1].^2-11).^2+(x[1]+x[2].^2-7).^2
	x0H = [10., 20.]
	himmelblau = ADNLPModel(fH, x0H)

	problem2 = ADNLPModel(x->-x[1]^3 + x[2]^2 + x[3]^2, ones(3))

	roz(x) = 100 *  (x[2] - x[1]^2)^2 + (x[1] - 1.0)^2
	rosenbrock = ADNLPModel(roz, [-1.2, 1.0])

	f(x) = x[1]^2 * (2*x[1] - 3) - 6*x[1]*x[2] * (x[1] - x[2] - 1)
	pb_du_cours = ADNLPModel(f, [-1.001, -1.001]) #ou [1.5, .5] ou [.5, .5]


	######################################### bfgs_quasi_newton_armijo ##################

	#Unit/Validation Tests
	using Logging, Test
    ep1 = 1e-6 + norm(grad(himmelblau, himmelblau.meta.x0)) * 1e-6
	sol = bfgs_quasi_newton_armijo(himmelblau, himmelblau.meta.x0) 
	@test norm(grad(himmelblau, sol)) ≤ ep1

    ep4 = 1e-6 + norm(grad(pb_du_cours, [1.5, .5])) * 1e-6
	sol = bfgs_quasi_newton_armijo(pb_du_cours, [1.5, .5]) 
	@test norm(grad(pb_du_cours, sol)) ≤ ep4
	@test sol ≈ [1, 0] atol = ep4
	@show sol

    ep5 = 1e-6 + norm(grad(pb_du_cours, [.5, .5])) * 1e-6
	sol = bfgs_quasi_newton_armijo(pb_du_cours, [.5, .5]) 
	@test norm(grad(pb_du_cours, sol)) ≤ ep4
	@test sol ≈ [1, 0] atol = ep4
	@show sol
end

TestSetException: Some tests did not pass: 3 passed, 2 failed, 0 errored, 0 broken.

### Exercice 4: application à un problème de grande taille

On va ajouter le package `OptimizationProblems` qui contient, comme son nom l'indique, une collection de problème d'optimisation disponible au format de `JuMP` (dans le sous-module `OptimizationProblems.PureJuMP`) et de `ADNLPModel` (dans le sous-module `OptimizationProblems.ADNLPProblems`).

In [ ]:
using ADNLPModels, OptimizationProblems.ADNLPProblems # Attention si vous ne faites pas using ADNLPModels avant ça ne fonctionne pas!

In [ ]:
n = 500
model = genrose(n=n)
@test typeof(model) <: ADNLPModel

Si vous le souhaitez, il est possible d'accéder à certaines informations sur le problème en accédant à son meta:

In [ ]:
using OptimizationProblems
OptimizationProblems.genrose_meta

Il est aussi possible d'accéder au meta de tous les problèmes

In [ ]:
OptimizationProblems.meta

Résoudre le problème `genrose` et un autre problème de la collection en utilisant vos algorithmes précédents.
Avant d'utiliser l'algorithme on testera que le problème est bien sans contrainte avec:

In [ ]:
unconstrained(nlp) #qui retourne vrai si `nlp` est un problème sans contraintes.

In [ ]:
# Use previous functions to solve genrose.